forge "http://forge.puppetlabs.com"

# Modules from the Puppet Forge
mod "puppetlabs/apt", '1.5.2'
mod "puppetlabs/firewall", '1.1.3'
mod "puppetlabs/git", '0.2.0'
mod "puppetlabs/ntp", '3.1.2'
mod "puppetlabs/stdlib", '4.3.2'
mod "willdurand/nodejs", '1.8.4'

# Github modules
